spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ko_vehicle
    driver-class-name: org.postgresql.Driver
    username: kovehicle
    password: 199433
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

